
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 14 13:08:47 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int diferenteA = 25;
  public static final int mayorQue = 20;
  public static final int asignaA = 13;
  public static final int comilladoSimple = 32;
  public static final int modula = 28;
  public static final int dosPuntos = 34;
  public static final int puntoYcoma = 36;
  public static final int corcheteB = 40;
  public static final int corcheteA = 39;
  public static final int coma = 35;
  public static final int entonces = 3;
  public static final int comilladoDobleA = 33;
  public static final int boleana = 11;
  public static final int caracter = 8;
  public static final int menorQue = 19;
  public static final int Division = 17;
  public static final int tambien = 26;
  public static final int mientrasque = 5;
  public static final int EOF = 0;
  public static final int mayorOigualA = 21;
  public static final int desplazaIzquierda = 23;
  public static final int para = 6;
  public static final int error = 1;
  public static final int doble = 10;
  public static final int obien = 29;
  public static final int Linea = 2;
  public static final int ERROR = 45;
  public static final int ademas = 4;
  public static final int llaveB = 42;
  public static final int llaveA = 41;
  public static final int incremento = 30;
  public static final int entera = 7;
  public static final int desplazaDerecha = 24;
  public static final int Identificador = 43;
  public static final int decremento = 31;
  public static final int Resta = 15;
  public static final int comentario = 27;
  public static final int parentesisB = 38;
  public static final int parentesisA = 37;
  public static final int igualA = 18;
  public static final int Multiplicacion = 16;
  public static final int Numero = 44;
  public static final int Suma = 14;
  public static final int flotante = 9;
  public static final int Main = 12;
  public static final int menorOigualA = 22;
}

